# Generated by Django 6.0.7 on 2026-08-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name="token",
            index=models.Index(
                fields=["created_at"], name="users_token_created_270259_idx"
            ),
        ),
    ]
