# Generated by Django 6.0.7 on 2026-07-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_token_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='token',
            name='telegram_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=64),
        ),
    ]
