# Generated by Django 6.0.7 on 2026-08-17 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='owners',
            field=models.ManyToManyField(related_name='sites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siteresponse',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='dashboard.site'),
        ),
        migrations.AddIndex(
            model_name='siteresponse',
            index=models.Index(fields=['site', '-checked_at'], name='dashboard_s_site_id_a6b3ef_idx'),
        ),
    ]
