# Generated by Django 6.0.7 on 2026-07-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='site',
            name='link',
            field=models.TextField(unique=True),
        ),
    ]
