# Generated by Django 6.0.7 on 2026-08-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="link",
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
