# Generated by Django 6.0.7 on 2026-08-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_site_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteresponse",
            name="response_time",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
